### PR TITLE
feat(mocks): implement sessions

### PR DESCRIPTION
**Pull request by abuecker**
feat(mocks): remove initial account information on create account

### CODE REVIEW

**Comment by abuecker** [comment]
@zrangerz @bondricek @kvhswong please review.  Thanks.

**Comment by bondricek** [comment]
do the sessions also work for v2 routes or is that needed?

**Comment by zrangerz** [comment]
Nope, /v3 only

--
Steve Mays
Sent with Airmail

**Comment by bondricek** [comment]
👍

**Pull request merged**
