### PR TITLE
fix(mocks): prune the schema for the create account route

### PR DESCRIPTION
**Pull request by abuecker**
- `profileId` we should be able to resolve from the token
- `advisorAgreementDate` we should be able to generate and set in the REST API
- `name`, `jointName`, `jointEmail` are all now set via the `docusignFormData`
- fixed error when sending blank response codes

### CODE REVIEW

**Comment by abuecker** [comment]
@johntowell @olmstead @zrangerz please review.

@johntowell will these changes break the platform tests?

**Comment by zrangerz** [comment]
Reviewed and understand the reasoning, +1

Steve

--
Steve Mays
Sent with Airmail

**Comment by johntowell** [comment]
We need name, jointName, and jointEmail separate since they are part of the docusign call itself. Not the form data.

**Comment by abuecker** [comment]
I'll put those back.  What does `name` mean?

**Comment by johntowell** [comment]
The signer's name. We use it in the json request like 
```
"signers": [
              {
                "name": "Bob Sample",
                "email": "john.towell+DOCUSIGN@trizic.com",
                "roleName": "Client",
                "recipientId": "1",
                "tabs": {
                  "textTabs": [
                    {
                      "tabLabel": "repcode",
                      "value": "AWNLTP"
                    },
                    {
                      "tabLabel": "FirmName",
                      "value": "NLI Wealth Management"
                    },
                    {
                      "tabLabel": "\\*FullName",
                      "value": "Bob Sample
```

Note we also use the same value for the "FullName" docusign form field. So we will need to pass it twice. Potentially the server could parse the docusign form fields and find it, but I like that the server doesn't care about the form fields right now. It just passes data through to docusign.

**Comment by abuecker** [comment]
@bump  made changes.

**Comment by johntowell** [comment]
👍

**Pull request merged**
