### PR TITLE
fix(mocks): revert changes to required profile.accounts fields

### PR DESCRIPTION
**Pull request by abuecker**

### CODE REVIEW

**Comment by olmstead** [comment]
Can leave changes to v3.js
👎

**Comment by abuecker** [comment]
I need those for the mocks.  If the fields aren't required, there is no guarantee they will be included.

**Comment by abuecker** [comment]
@olmstead rebased.  Please review.

**Comment by olmstead** [comment]
Ah, gotcha, that makes sense, whole thing is kind of a catch 22.  So you'd rather just not have the data at all for now?  Can run locally against a branch I suppose?

**Comment by abuecker** [comment]
I need this data for the mocks.  Even though those fields are not marked as required, I sure would hope that we're getting the id and description returned via the endpoint.

**Comment by olmstead** [comment]
👍

**Pull request merged**
