### PR TITLE
feat(HOME-3512): updating docs for V10 AccountDocuments

### PR DESCRIPTION
**Pull request by DatChive**
image
image
image
image
image
image

### CODE REVIEW

**Comment by zrangerz** [comment]
Thanks to @bondricek I now remember how to see/test. Checking this out now.

**Comment by bondricek** [comment]
i think the MFA thing should be removed, i believe that is copy 🍝  from older routes

**Comment by DatChive** [comment]
Yup, removed all the token/expiry/403. Shifted the description of the get {documentId} route so that it's actually in the GET box

**Comment by DatChive** [comment]
image

**Pull request merged**
