### PR TITLE
feat(accounts): add accountOpeningId to request

### PR DESCRIPTION
**Pull request by johntowell**
Closes CU2-195

The accountOpeningId will only be used for the initial account opening during onboarding.

@olmstead @abuecker @antoinemeyer

### CODE REVIEW

**Comment by olmstead** [comment]
👍

**Comment by abuecker** [comment]
What is this used for?  Can we look the id up on the server side?

**Comment by johntowell** [comment]
This is the id of the account opening used to store accountType, profileId, and questionnaire for the create profile route.

I'm not sure if I like it though. I guess we could search for an account opening that is NEW but without a docusign envelope id and assume it is an opening in this state.

**Comment by abuecker** [comment]
There can only be one account opening at a time.  Can we resolve the opening id from the profile id on the server side in the POST create account?

**Comment by johntowell** [comment]
I think I can figure it out from server side.

**Comment by abuecker** [comment]
Cool.  On a related note, #54 removes the account opening id from the profile.

**Pull request closed without merging**
