### PR TITLE
fix(mocks): generate the full range of data points for performance

### PR DESCRIPTION
**Pull request by abuecker**

### CODE REVIEW

**Comment by abuecker** [comment]
@olmstead @johntowell @eweise please review.  It's a small PR if you ignore the shrinkwrap diff.  Basically, this change generates daily data points for the queried range.

**Comment by olmstead** [comment]
👍

**Comment by johntowell** [comment]
I created a more realistic data series for the v2 route if you want to use it.

**Comment by johntowell** [comment]
```
      if (reqToMock.uri === '/v2/consumer/account/data') {
        server[reqToMock.method](reqToMock.uri, function(req, res, next) {
          let mock = reqToMock.mockByCode(200);
          mock.status = 'OK';
          mock.data.accountSeries = [];
          let date = getBeginningDateFromPeriod(req.body.period);
          let percent = 0;
          let percents = [-4.3, -0.43, -0.38, -0.23, -0.12,
            0.13, 0.26, 0.37, 0.46, 0.56, 0.67, 0.73, 0.88, 0.97, 3.2];

          while (date.isBefore(moment())) {
            mock.data.accountSeries.push(
              [date.toDate().getTime(), percent]
            );
            date = date.add(1, 'days');
            percent = percent +
              percents[Math.floor(Math.random() * percents.length)];
          }

          res.send(mock);
          return next();
        });
      }
```

**Comment by abuecker** [comment]
@johntowell good idea.  Borrowed from your example.  Data look much more reasonable.

screenshot 2016-06-10 08 22 13

**Comment by johntowell** [comment]
👍

**Pull request merged**
