### PR TITLE
fix: fix syntax errors on v3 performance route

### PR DESCRIPTION
**Pull request by johntowell**
@olmstead @abuecker @eweise @antoinemeyer 

fixes the schema 
  * remove "period" from required
  * move the "required" attribute up one level, parallel with properties
  * add additionalProperties: false

### CODE REVIEW

**Comment by olmstead** [comment]
I'm not convinced that "add additionalProperties: false" is really what we want.  Seems like what we should be testing for on the platform side is backwards compatibility, so we should be able to add properties, but not modify or remove existing.  Currently changes that are backwards compatible will break tests.

**Comment by johntowell** [comment]
Why will changes break tests? Can't we change our tests when we change our implementation?

**Comment by johntowell** [comment]
additionalProperties: false will just ensure that our schema is in sync with our implementation, which it should be

We can still make backwards compatible changes to routes (ie adding new properties) we just need to update both the schema and implementation when we do so.

**Comment by olmstead** [comment]
Right, but you have to do that shuffle where you merge both the docs and the implementation at the same time.  Why not just allow backwards compatible changes?

**Comment by johntowell** [comment]
"but you have to do that shuffle where you merge both the docs and the implementation at the same time" - that part is broken I agree

The fact that our dependency on api-docs from platform is broken shouldn't prevent us from creating the correct schema.

We should version our schema dependency in platform

**Comment by olmstead** [comment]
I don' think we test for backwards compatibility. Theoretically, we could successfully keep the implementation and the docs in sync, while breaking clients.   We have to assume that none of us would ever make a change that wasn't backwards compatible.

**Comment by johntowell** [comment]
"We have to assume that none of us would ever make a change that wasn't backwards compatible." - This seems tangential to adding additionalProperties: false

**Comment by olmstead** [comment]
👍  John and I talked, agreed we need a long term solution for testing the client/api contract, but don't have one yet.  Use additionalProperties: false for now to implementation/docs in sync.

**Pull request merged**
