### PR TITLE
fix(api): remove account opening id and change portfolio id to a UUID

### PR DESCRIPTION
**Pull request by abuecker**

### CODE REVIEW

**Comment by abuecker** [comment]
@zrangerz @johntowell @olmstead please review.  Title says it all.  It's a small change.  Thanks!

**Comment by abuecker** [comment]
@bump

**Comment by johntowell** [comment]
I don't think we have a uuid for model portfolio

**Comment by abuecker** [comment]
When I see field types as a number, I assume it's a database generated key.  If that's not the case, I'll change it back.  Otherwise, we should be returning UUID's.

**Comment by johntowell** [comment]
It is a database generated key, we don't have a uuid for that table. Only Account and ClientAccount I think.

**Comment by abuecker** [comment]
Oh, gotcha.  Can we add one?

**Comment by johntowell** [comment]
It's a big change, since we need to update 3 other rest routes besides this one. Also we need to backfill the database for existing model portfolios.

Why do we need it?

**Comment by abuecker** [comment]
Returning database keys is a potential security attack vector.  We should always use UUIDs.

I'll revert those changes for now.  We can do it post 7/15.  Here is a story to get the work done:

https://trizic.atlassian.net/browse/CU2-244

**Comment by abuecker** [comment]
Updated.

**Comment by johntowell** [comment]
👍

**Comment by johntowell** [comment]
I merged it to sync with my changes in platform

**Pull request merged**
